import { zip } from './xlsxCore.js'

      const dec=new TextDecoder('utf-8'), enc=new TextEncoder();
      const NS='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
      const RNS='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
      const PRNS='http://schemas.openxmlformats.org/package/2006/relationships';
      const MAX_XLSX_INPUT_BYTES=64*1024*1024, MAX_ZIP_ENTRIES=4096, MAX_ENTRY_UNCOMPRESSED_BYTES=64*1024*1024, MAX_TOTAL_UNCOMPRESSED_BYTES=192*1024*1024;
      function elems(node,name){return [...node.getElementsByTagNameNS('*',name)]}
      function rd16(d,o){return d.getUint16(o,true)} function rd32(d,o){return d.getUint32(o,true)}
      async function inflateRaw(bytes,maxBytes=MAX_ENTRY_UNCOMPRESSED_BYTES){
        if(typeof DecompressionStream==='undefined')throw new Error('Этот браузер не поддерживает распаковку XLSX. Используйте настольную версию приложения.');
        const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw')),reader=stream.getReader(),chunks=[];let total=0;
        try{
          while(true){const {value,done}=await reader.read();if(done)break;total+=value.byteLength;if(total>maxBytes){await reader.cancel();throw new Error('XLSX содержит слишком большой распакованный элемент для 32-битной сборки.')}chunks.push(value)}
        }catch(error){
          if(String(error?.message||'').includes('слишком большой'))throw error;
          throw new Error('Повреждён XLSX: не удалось распаковать данные.');
        }finally{reader.releaseLock?.()}
        const out=new Uint8Array(total);let offset=0;for(const chunk of chunks){out.set(chunk,offset);offset+=chunk.byteLength}return out;
      }
      async function unzip(input){
        const bytes=input instanceof Uint8Array?input:new Uint8Array(input);
        if(bytes.byteLength<22)throw new Error('Файл не похож на корректный XLSX/ZIP.');
        if(bytes.byteLength>MAX_XLSX_INPUT_BYTES)throw new Error('XLSX больше 64 МБ. Для 32-битной сборки импорт такого файла заблокирован.');
        const d=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);
        let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(rd32(d,i)===0x06054b50){eocd=i;break}}
        if(eocd<0)throw new Error('Файл не похож на корректный XLSX/ZIP.');
        const count=rd16(d,eocd+10), cdOff=rd32(d,eocd+16);if(count>MAX_ZIP_ENTRIES)throw new Error('XLSX содержит слишком много внутренних файлов.');if(cdOff>=eocd)throw new Error('Повреждён центральный каталог XLSX.');
        let p=cdOff,totalUncompressed=0;const out=new Map();
        for(let i=0;i<count;i++){
          if(p+46>bytes.length||rd32(d,p)!==0x02014b50)throw new Error('Повреждён центральный каталог XLSX.');
          const flags=rd16(d,p+8), method=rd16(d,p+10), csize=rd32(d,p+20), usize=rd32(d,p+24), nlen=rd16(d,p+28), xlen=rd16(d,p+30), clen=rd16(d,p+32), loff=rd32(d,p+42), next=p+46+nlen+xlen+clen;
          if(next>bytes.length||nlen>2048)throw new Error('Повреждён центральный каталог XLSX.');
          if(flags&1)throw new Error('XLSX защищён паролем. Снимите защиту и повторите импорт.');
          if(usize>MAX_ENTRY_UNCOMPRESSED_BYTES)throw new Error('XLSX содержит слишком большой распакованный элемент для 32-битной сборки.');
          totalUncompressed+=usize;if(totalUncompressed>MAX_TOTAL_UNCOMPRESSED_BYTES)throw new Error('XLSX распаковывается более чем в 192 МБ. Импорт заблокирован для защиты памяти.');
          const name=dec.decode(bytes.slice(p+46,p+46+nlen));
          if(loff+30>bytes.length||rd32(d,loff)!==0x04034b50)throw new Error('Повреждён XLSX: не найдена локальная запись '+name);
          const ln=rd16(d,loff+26), lx=rd16(d,loff+28), start=loff+30+ln+lx,end=start+csize;if(start>bytes.length||end>bytes.length)throw new Error('Повреждён XLSX: обрезаны данные '+name);
          const compressed=bytes.slice(start,end);let data;if(method===0)data=compressed;else if(method===8)data=await inflateRaw(compressed,MAX_ENTRY_UNCOMPRESSED_BYTES);else throw new Error('Неподдерживаемый метод сжатия XLSX: '+method);
          if(data.byteLength!==usize)throw new Error('Повреждён XLSX: неверный размер распакованного элемента '+name);
          out.set(name,data);p=next;
        }
        return out;
      }
      function xml(bytes){const doc=new DOMParser().parseFromString(dec.decode(bytes),'application/xml');if(doc.getElementsByTagName('parsererror').length)throw new Error('Повреждён XLSX: некорректный XML.');return doc}
      function serialize(doc){return enc.encode(new XMLSerializer().serializeToString(doc))}
      function normalizeTarget(t){t=String(t||'').replace(/\\/g,'/');if(t.startsWith('/'))return t.slice(1);if(t.startsWith('xl/'))return t;return 'xl/'+t.replace(/^\.\//,'')}
        function sharedStrings(files){const b=files.get('xl/sharedStrings.xml');if(!b)return[];const d=xml(b);return elems(d,'si').map(si=>elems(si,'t').map(t=>t.textContent||'').join(''))}
        function cellText(c,shared){const t=c.getAttribute('t')||'';if(t==='s'){const v=elems(c,'v')[0];return v?shared[Number(v.textContent)]??'':''}if(t==='inlineStr')return elems(c,'t').map(x=>x.textContent||'').join('');const v=elems(c,'v')[0];return v?v.textContent||'':''}
        function clearChildren(n){while(n.firstChild)n.removeChild(n.firstChild)}
        function setCell(c,value){clearChildren(c);if(value===null||value===undefined||value===''){c.removeAttribute('t');return}if(typeof value==='number'&&Number.isFinite(value)){c.removeAttribute('t');const v=c.ownerDocument.createElementNS(NS,'v');v.textContent=String(value);c.appendChild(v);return}c.setAttribute('t','inlineStr');const is=c.ownerDocument.createElementNS(NS,'is'),t=c.ownerDocument.createElementNS(NS,'t');t.setAttribute('xml:space','preserve');t.textContent=String(value);is.appendChild(t);c.appendChild(is)}
        function replaceTokens(text,vals){const exact=String(text).match(/^\s*\{\{([A-Z0-9_]+)\}\}\s*$/);if(exact&&Object.prototype.hasOwnProperty.call(vals,exact[1]))return vals[exact[1]];let out=String(text);for(const [k,v] of Object.entries(vals))out=out.split('{{'+k+'}}').join(v??'');return out}
        function replaceRow(row,shared,vals){for(const c of elems(row,'c')){const old=cellText(c,shared);if(old.includes('{{'))setCell(c,replaceTokens(old,vals))}}
        function rowNum(row){return Number(row.getAttribute('r')||0)}
        function setRowNumber(row,n){row.setAttribute('r',String(n));for(const c of elems(row,'c')){const ref=c.getAttribute('r');if(ref)c.setAttribute('r',ref.replace(/\d+$/,String(n)))}}
        function shiftRange(ref,after,delta){return String(ref).replace(/(\$?[A-Z]{1,3}\$?)(\d+)/g,(m,col,r)=>{r=Number(r);return col+String(r>after?r+delta:r)})}
        function shiftAfter(doc,after,delta){if(!delta)return;const rows=elems(doc,'row').filter(r=>rowNum(r)>after).sort((a,b)=>delta>0?rowNum(b)-rowNum(a):rowNum(a)-rowNum(b));for(const r of rows)setRowNumber(r,rowNum(r)+delta);for(const tag of ['mergeCell','hyperlink'])for(const n of elems(doc,tag)){const ref=n.getAttribute('ref');if(ref)n.setAttribute('ref',shiftRange(ref,after,delta))}const dim=elems(doc,'dimension')[0];if(dim?.getAttribute('ref'))dim.setAttribute('ref',shiftRange(dim.getAttribute('ref'),after,delta))}
        function rowAt(doc,n){return elems(doc,'row').find(r=>rowNum(r)===n)||null}
        function clearRow(row){for(const c of elems(row,'c'))setCell(c,'')}
        function colOf(c){return String(c.getAttribute('r')||'').replace(/\d+$/,'')}
        function cellInRow(row,col){return elems(row,'c').find(c=>colOf(c)===col)||null}
        function setCol(row,col,value){const c=cellInRow(row,col);if(c)setCell(c,value)}
        function setRef(doc,ref,value){const c=elems(doc,'c').find(c=>c.getAttribute('r')===ref);if(c)setCell(c,value)}
        function mergeRangeRows(ref){const nums=String(ref||'').match(/\d+/g);if(!nums?.length)return null;const a=Number(nums[0]),b=Number(nums[nums.length-1]);return {a:Math.min(a,b),b:Math.max(a,b)}}
        function ensureMergeCells(doc){let mc=elems(doc,'mergeCells')[0];if(mc)return mc;mc=doc.createElementNS(NS,'mergeCells');const root=doc.documentElement,sheetData=elems(doc,'sheetData')[0],after=sheetData?.nextSibling||null;root.insertBefore(mc,after);return mc}
        function setMergedCenteredRow(doc,row,value,styleCell,maxCol){
          const rn=rowNum(row),last=colName(maxCol||maxColNum(doc)||11),mc=ensureMergeCells(doc);
          for(const m of [...elems(mc,'mergeCell')]){const rr=mergeRangeRows(m.getAttribute('ref'));if(rr&&rn>=rr.a&&rn<=rr.b)m.parentNode.removeChild(m)}
          let style=styleCell?.getAttribute('s')||elems(row,'c').find(c=>c.getAttribute('s'))?.getAttribute('s')||'';
          for(const c of [...elems(row,'c')])c.parentNode.removeChild(c);
          const c=doc.createElementNS(NS,'c');c.setAttribute('r',`A${rn}`);if(style)c.setAttribute('s',style);setCell(c,value);row.appendChild(c);
          const m=doc.createElementNS(NS,'mergeCell');m.setAttribute('ref',`A${rn}:${last}${rn}`);mc.appendChild(m);mc.setAttribute('count',String(elems(mc,'mergeCell').length));
        }
        function normalizeSignatureRows(doc,shared,model,maxCol){
          if(!model?.signTitle&&!model?.signLine)return;
          const rows=elems(doc,'row');
          let titleRow=null,titleCell=null,signRow=null;
          for(const row of rows){
            const cs=elems(row,'c'),vals=cs.map(c=>cellText(c,shared)),low=vals.join(' ').toLowerCase();
            if(!titleRow&&model.signTitle&&low.includes('командир автомобильной роты')){titleRow=row;titleCell=cs.find(c=>cellText(c,shared).toLowerCase().includes('командир автомобильной роты'))||cs[0]||null}
            if(!signRow&&model.signLine){
              const rank=String(model.signLine.rank||'').trim().toLowerCase(),comm=String(model.signLine.commander||'').trim().toLowerCase();
              if((rank&&vals.some(v=>String(v).trim().toLowerCase()===rank))||(comm&&vals.some(v=>String(v).trim().toLowerCase()===comm)))signRow=row;
            }
          }
          if(titleRow)setMergedCenteredRow(doc,titleRow,model.signTitle,titleCell,maxCol);
          if(signRow&&model.signLine){
            const styleCell=titleCell||elems(signRow,'c')[0]||null;
            setMergedCenteredRow(doc,signRow,`${model.signLine.rank||''}__________${model.signLine.commander||''}`,styleCell,maxCol);
          }
        }
        function replaceBlock(doc,start,count,records,fill){if(count<1)return 0;const originals=[];for(let i=0;i<count;i++){const r=rowAt(doc,start+i);if(r)originals.push(r)}if(!originals.length)return 0;const clones=originals.map(r=>r.cloneNode(true)),end=start+count-1,delta=records.length-count;shiftAfter(doc,end,delta);for(const r of originals)r.parentNode.removeChild(r);const data=elems(doc,'sheetData')[0];const before=elems(data,'row').filter(r=>rowNum(r)>=start+records.length).sort((a,b)=>rowNum(a)-rowNum(b))[0]||null;records.forEach((rec,i)=>{const cp=clones[Math.min(i,clones.length-1)].cloneNode(true);setRowNumber(cp,start+i);clearRow(cp);fill(cp,rec,i);data.insertBefore(cp,before)});return delta}
        function workbookEntries(files){const wb=files.get('xl/workbook.xml'), rel=files.get('xl/_rels/workbook.xml.rels');if(!wb||!rel)return[];const wd=xml(wb),rd=xml(rel),rmap=new Map(elems(rd,'Relationship').map(r=>[r.getAttribute('Id'),normalizeTarget(r.getAttribute('Target'))]));return elems(wd,'sheet').map((s,i)=>{const rid=s.getAttributeNS(RNS,'id')||s.getAttribute('r:id');return {name:s.getAttribute('name')||`Sheet${i+1}`,rid,path:rmap.get(rid)||null,index:i}}).filter(x=>x.path&&files.has(x.path))}
        function colName(n){let s='';while(n>0){n--;s=String.fromCharCode(65+(n%26))+s;n=Math.floor(n/26)}return s||'A'}
        function maxColNum(doc){let max=0;for(const c of elems(doc,'c')){const ref=c.getAttribute('r')||'', letters=ref.replace(/\d/g,'');let n=0;for(const ch of letters)n=n*26+(ch.charCodeAt(0)-64);max=Math.max(max,n)}return max}
        function analyze(files,entry,shared){const doc=xml(files.get(entry.path)), rows=elems(doc,'row'), texts=rows.map(r=>({r:rowNum(r),vals:elems(r,'c').map(c=>cellText(c,shared))}));const all=texts.flatMap(x=>x.vals).join('\n');const hasTrip=all.includes('{{TRIP_NO}}'),hasMaterials=all.includes('{{MAT_NAME}}'),hasTitle=all.includes('{{TITLE}}');const header=texts.find(x=>x.vals.some(v=>String(v).trim().toLowerCase()==='№ п/п'))?.r||null;const total=texts.find(x=>x.vals.some(v=>String(v).trim().toUpperCase()==='ИТОГО'))?.r||null;const note=texts.find(x=>x.vals.some(v=>String(v).trim().toLowerCase().startsWith('примечание:'))) ?.r||null;const maxCol=maxColNum(doc);let matRows=[];if(total){for(const x of texts.filter(x=>x.r>total&&(!note||x.r<note)).sort((a,b)=>a.r-b.r)){const name=String((maxCol>11?x.vals[4]:x.vals[3])||'').trim();const nonempty=x.vals.some(v=>String(v??'').trim()!=='');if(!nonempty){if(matRows.length)break;continue}if(name&&name.toUpperCase()!=='ИТОГО')matRows.push(x.r);else if(matRows.length)break}}
          const native=!!(header&&total);let score=(hasTrip?100:0)+(entry.name==='3263'?50:0)+(native?20:0)+(all.includes('Расчетная ведомость')?10:0)+(maxCol===11?5:0);return {...entry,doc,hasTrip,hasMaterials,hasTitle,headerRow:header,totalRow:total,noteRow:note,maxCol,materialRows:matRows,tripBaseCount:header&&total?Math.max(1,total-header-1):0,materialBaseCount:matRows.length,native,score}}
        function inspectFiles(files){const shared=sharedStrings(files),entries=workbookEntries(files), analyses=entries.map(e=>analyze(files,e,shared));const token=analyses.find(a=>a.hasTrip);const base=analyses.find(a=>a.name==='3263'&&a.native)||analyses.filter(a=>a.native).sort((a,b)=>b.score-a.score)[0]||token||analyses[0];return {sheet:base?.path||null,sheetName:base?.name||null,mode:token?'token':base?.native?'native':'unknown',hasTrip:!!token,hasMaterials:!!token?.hasMaterials,hasTitle:!!token?.hasTitle,has3263:analyses.some(a=>a.name==='3263'&&a.native),has3099:analyses.some(a=>a.name==='3099'&&a.native),sheetNames:analyses.map(a=>a.name),score:base?.score||0}}
        async function inspect(bytes){const files=await unzip(bytes);return inspectFiles(files)}
        function excelDateFromRu(s){const m=String(s||'').match(/^(\d{2})\.(\d{2})\.(\d{4})$/);if(!m)return s||'';const d=Date.UTC(+m[3],+m[2]-1,+m[1]),epoch=Date.UTC(1899,11,30);return Math.round((d-epoch)/86400000)}
        function chooseSource(analyses,model){const token=analyses.find(a=>a.hasTrip);if(token)return token;if(model?.hasMotohours){const special=analyses.find(a=>a.name===String(model.shortNo)&&a.native&&a.maxCol>11)||analyses.find(a=>a.name==='3099'&&a.native);if(special)return special}return analyses.find(a=>a.name==='3263'&&a.native)||analyses.find(a=>a.name===String(model?.shortNo)&&a.native)||analyses.find(a=>a.native)||analyses[0]}
        function tokenRender(doc,shared,model){function findRepeatRow(token){return elems(doc,'row').find(r=>elems(r,'c').some(c=>cellText(c,shared).includes('{{'+token+'}}')))||null}
          function expand(token,records){const row=findRepeatRow(token);if(!row)return;const n=rowNum(row),base=row.cloneNode(true),parent=row.parentNode,next=row.nextSibling,count=records.length,delta=count-1;shiftAfter(doc,n,delta);parent.removeChild(row);for(let i=0;i<count;i++){const copy=base.cloneNode(true);setRowNumber(copy,n+i);replaceRow(copy,shared,records[i]);parent.insertBefore(copy,next)}}
          const trips=(model.tripRows||[]).map(r=>({TRIP_NO:r[0],TRIP_DATE:r[1],TRIP_WAYBILL:r[2],ODO_START:r[3],ODO_END:r[4],GSM_START:r[5],GSM_RECEIVED:r[6],GSM_SPENT:r[7],GSM_END:r[8],KM:r[9],NOTE:r[10]}));expand('TRIP_NO',trips);
          const mats=(model.materialRows||[]).map(r=>({MAT_NAME:r[3],MAT_START:r[5],MAT_RECEIVED:r[6],MAT_SPENT:r[7],MAT_END:r[8]}));expand('MAT_NAME',mats);
          const vars={TITLE:model.title||'',NORM:model.norm||'',VEHICLE:model.vehicleModel?`${model.vehicleModel} №${model.vehicleNo||''}`:'',VEHICLE_MODEL:model.vehicleModel||'',VEHICLE_NO:model.vehicleNo||'',SHORT_NO:model.shortNo||'',PERIOD:model.period||'',DATE_FROM:model.dateFrom||'',DATE_TO:model.dateTo||'',UNIT:model.signTitle||'',RANK:model.signLine?.rank||'',COMMANDER:model.signLine?.commander||'',FIRST_ODO:model.totalRow?.[3]??'',LAST_ODO:model.totalRow?.[4]??'',TOTAL_KM:model.totalRow?.[9]??''};for(const row of elems(doc,'row'))replaceRow(row,shared,vars);normalizeSignatureRows(doc,shared,model,maxColNum(doc));return doc}
        function nativeRender(source,shared,model){const doc=xml(serialize(source.doc)),special=source.maxCol>11&&model?.hasMotohours;const tripRecords=(model.tripRows||[]).length?(model.tripRows||[]):[null];const tripStart=source.headerRow+1;const tripDelta=replaceBlock(doc,tripStart,source.tripBaseCount,tripRecords,(row,r)=>{if(!r)return;setCol(row,'A',r[0]);setCol(row,'B',excelDateFromRu(r[1]));setCol(row,'C',r[2]);if(special){setCol(row,'D',r[3]);setCol(row,'E','');setCol(row,'F',r[4]);setCol(row,'G','');setCol(row,'H',r[5]);setCol(row,'I',r[6]);setCol(row,'J',r[7]);setCol(row,'K',r[8]);setCol(row,'L',r[9]);setCol(row,'M',r[10]);const a=Number(r[3]),b=Number(r[4]);setCol(row,'N',Number.isFinite(a)&&Number.isFinite(b)?b-a:'');setCol(row,'O','')}else{setCol(row,'D',r[3]);setCol(row,'E',r[4]);setCol(row,'F',r[5]);setCol(row,'G',r[6]);setCol(row,'H',r[7]);setCol(row,'I',r[8]);setCol(row,'J',r[9]);setCol(row,'K',r[10])}});
          const totalAt=source.totalRow+tripDelta,total=rowAt(doc,totalAt);if(total){clearRow(total);setCol(total,'B','ИТОГО');if(special){setCol(total,'D',model.totalRow?.[3]??'');setCol(total,'F',model.totalRow?.[4]??'');setCol(total,'L',model.totalRow?.[9]??'');const a=Number(model.totalRow?.[3]),b=Number(model.totalRow?.[4]);setCol(total,'N',Number.isFinite(a)&&Number.isFinite(b)?b-a:'')}else{setCol(total,'D',model.totalRow?.[3]??'');setCol(total,'E',model.totalRow?.[4]??'');setCol(total,'J',model.totalRow?.[9]??'')}}
          if(source.materialBaseCount){const matStart=source.totalRow+tripDelta+1,mats=model.materialRows||[];replaceBlock(doc,matStart,source.materialBaseCount,mats,(row,r)=>{if(special){setCol(row,'E',r[3]);setCol(row,'H',r[5]);setCol(row,'I',r[6]);setCol(row,'J',r[7]);setCol(row,'K',r[8])}else{setCol(row,'D',r[3]);setCol(row,'F',r[5]);setCol(row,'G',r[6]);setCol(row,'H',r[7]);setCol(row,'I',r[8])}})}
          setRef(doc,'A1',model.title||'');setRef(doc,'A2',model.norm||'');
          for(const c of elems(doc,'c')){const t=cellText(c,shared),low=t.toLowerCase();if(/^ДТ(?=\s|$)/i.test(t))setCell(c,t.replace(/^ДТ(?=\s|$)/i,'Дт'));if(t.includes('#REF!')||elems(c,'f').some(f=>(f.textContent||'').includes('#REF!'))){setCell(c,'');continue}if(low.includes('командир автомобильной роты')&&model.signTitle)setCell(c,model.signTitle);else if(low.trim()==='капитан'&&model.signLine?.rank)setCell(c,model.signLine.rank);else if(t.includes('А. Геращенко')&&model.signLine?.commander)setCell(c,model.signLine.commander);else if(low.includes('данные указанные в расчетной ведомости')&&low.includes('подтверждаю'))setCell(c,`Данные указанные в расчетной ведомости по пробегу и расходу горючего ${model.vehicleModel} №${model.vehicleNo} подтверждаю.`)}
          normalizeSignatureRows(doc,shared,model,source.maxCol);return doc}
        function safeSheetName(name,i){let s=String(name||`Ведомость ${i}`).replace(/[\\\/?*\[\]:]/g,' ').trim();return (s||`Ведомость ${i}`).slice(0,31)}
        function sheetRelPath(path){const m=String(path).match(/^xl\/worksheets\/(.+\.xml)$/);return m?`xl/worksheets/_rels/${m[1]}.rels`:null}
        function updateWorkbook(files,rendered){const wbd=xml(files.get('xl/workbook.xml')),sheets=elems(wbd,'sheets')[0];while(sheets.firstChild)sheets.removeChild(sheets.firstChild);rendered.forEach((r,i)=>{const n=wbd.createElementNS(NS,'sheet');n.setAttribute('name',safeSheetName(r.model.name||r.model.shortNo,i+1));n.setAttribute('sheetId',String(i+1));n.setAttributeNS(RNS,'r:id',`rIdGSM${i+1}`);sheets.appendChild(n)});const defs=elems(wbd,'definedNames')[0];if(defs)defs.parentNode.removeChild(defs);for(const v of elems(wbd,'workbookView')){v.setAttribute('firstSheet','0');v.setAttribute('activeTab','0')}files.set('xl/workbook.xml',serialize(wbd));
          const rd=xml(files.get('xl/_rels/workbook.xml.rels')),root=rd.documentElement;for(const r of elems(rd,'Relationship')){const typ=r.getAttribute('Type')||'';if(typ.endsWith('/worksheet')||typ.endsWith('/calcChain'))r.parentNode.removeChild(r)}rendered.forEach((r,i)=>{const n=rd.createElementNS(PRNS,'Relationship');n.setAttribute('Id',`rIdGSM${i+1}`);n.setAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet');n.setAttribute('Target',`worksheets/sheet${i+1}.xml`);root.appendChild(n)});files.set('xl/_rels/workbook.xml.rels',serialize(rd));
          files.delete('xl/calcChain.xml');const ct=xml(files.get('[Content_Types].xml')),ctroot=ct.documentElement;for(const o of elems(ct,'Override'))if(o.getAttribute('PartName')==='/xl/calcChain.xml')o.parentNode.removeChild(o);rendered.forEach((r,i)=>{const part=`/xl/worksheets/sheet${i+1}.xml`;if(!elems(ct,'Override').some(o=>o.getAttribute('PartName')===part)){const n=ct.createElementNS('http://schemas.openxmlformats.org/package/2006/content-types','Override');n.setAttribute('PartName',part);n.setAttribute('ContentType','application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml');ctroot.appendChild(n)}});files.set('[Content_Types].xml',serialize(ct))}
        function buildBook(files,models){const shared=sharedStrings(files),analyses=workbookEntries(files).map(e=>analyze(files,e,shared)),rendered=[];for(const model of models){const source=chooseSource(analyses,model);if(!source)throw new Error('В шаблоне не найден подходящий лист.');let doc;if(source.hasTrip)doc=tokenRender(xml(files.get(source.path)),shared,model);else if(source.native)doc=nativeRender(source,shared,model);else throw new Error('Шаблон не распознан. Используйте исходную книгу с листом 3263 или размеченный шаблон.');const relp=sheetRelPath(source.path),rel=relp&&files.get(relp)?files.get(relp):null;rendered.push({model,source,xml:serialize(doc),rel})}
          for(const name of [...files.keys()])if(/^xl\/worksheets\/sheet\d+\.xml$/.test(name)||/^xl\/worksheets\/_rels\/sheet\d+\.xml\.rels$/.test(name))files.delete(name);rendered.forEach((r,i)=>{files.set(`xl/worksheets/sheet${i+1}.xml`,r.xml);if(r.rel)files.set(`xl/worksheets/_rels/sheet${i+1}.xml.rels`,r.rel)});updateWorkbook(files,rendered);return zip([...files.entries()].map(([name,data])=>({name,data})))}
        async function renderBook(templateBytes,models){if(!models?.length)throw new Error('Нет ведомостей для экспорта');const files=await unzip(templateBytes);return buildBook(files,models)}
        async function render(templateBytes,model){return renderBook(templateBytes,[model])}
        function cellRef(doc,ref,shared){const c=elems(doc,'c').find(x=>x.getAttribute('r')===ref);return c?cellText(c,shared):''}
        function colText(row,col,shared){const c=cellInRow(row,col);return c?cellText(c,shared):''}
        function excelSerialIso(v){const n=Number(String(v??'').replace(',','.'));if(!Number.isFinite(n)||n<1)return'';const d=new Date(Date.UTC(1899,11,30)+Math.floor(n)*86400000);return d.toISOString().slice(0,10)}
        function workbookDate(v){const x=String(v??'').trim();if(!x)return'';if(/^\d+(?:\.\d+)?$/.test(x))return excelSerialIso(x);let m=x.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);if(m)return `${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`;m=x.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:''}
        const RU_MONTHS={января:1,февраля:2,марта:3,апреля:4,мая:5,июня:6,июля:7,августа:8,сентября:9,октября:10,ноября:11,декабря:12};
        function isoRuDate(d,m,y){const n=RU_MONTHS[String(m||'').toLowerCase()];return n?`${y}-${String(n).padStart(2,'0')}-${String(d).padStart(2,'0')}`:''}
        function periodFromTitle(title){const t=String(title||'').replace(/\s+/g,' ');const m=t.match(/за\s+(\d{1,2})\s+([а-яё]+)\s+(\d{4})\s*(?:года?|г\.?)?\s*[-–—]\s*(\d{1,2})\s+([а-яё]+)\s+(\d{4})/i);if(!m)return null;const start=isoRuDate(m[1],m[2],m[3]),end=isoRuDate(m[4],m[5],m[6]);return start&&end?{start,end,reportMonth:end.slice(0,7)}:null}
        function matKey(s){return String(s??'').replace(/[«»]/g,'"').replace(/\s+/g,' ').replace(/^масло\s+/i,'').replace(/^дт(?=\s|$)/i,'ДТ').trim().toLowerCase()}
        function canonicalMaterial(raw,catalog){const k=matKey(raw);for(const m of catalog||[]){for(const a of [m.name,...(m.aliases||[])])if(matKey(a)===k)return {name:m.name,unknown:false}}const clean=String(raw||'').replace(/[«»]/g,'"').replace(/\s+/g,' ').trim();if(/^дт\b/i.test(clean))return {name:clean.replace(/^дт(?=\s|$)/i,'ДТ'),unknown:true};if(/^масло\s+/i.test(clean))return {name:clean.replace(/^масло\s+/i,'Масло '),unknown:true};return {name:`Масло ${clean}`,unknown:true}}
        function parseMaterialCell(text,catalog,unknown){const out={};for(const ln0 of String(text||'').split(/\r?\n/)){const ln=ln0.trim();if(!ln)continue;const m=ln.match(/^([+-]?\d+(?:[.,]\d+)?)\s+(.+)$/);if(!m)continue;const value=Number(m[1].replace(',','.'));if(!Number.isFinite(value))continue;const cm=canonicalMaterial(m[2],catalog);out[cm.name]=value;if(cm.unknown)unknown.add(cm.name)}return out}
        function numCell(v){const x=Number(String(v??'').replace(',','.'));return Number.isFinite(x)?x:null}
        function vehicleForSheet(a,vehicles,shared){let v=(vehicles||[]).find(x=>String(x.shortNo)===String(a.name).trim());if(v)return v;const title=cellRef(a.doc,'A1',shared);const m=String(title).match(/№\s*([0-9]{4})/);return m?(vehicles||[]).find(x=>String(x.shortNo)===m[1])||null:null}
        function parseNativeSheet(a,shared,vehicle,catalog,unknown){if(!a.native||!a.headerRow||!a.totalRow)return[];const special=a.maxCol>11&&!!vehicle.hasMotohours,trips=[];for(let rn=a.headerRow+1;rn<a.totalRow;rn++){const row=rowAt(a.doc,rn);if(!row)continue;const date=workbookDate(colText(row,'B',shared)),number=String(colText(row,'C',shared)||'').trim();const odoStart=numCell(colText(row,'D',shared)),odoEnd=numCell(colText(row,special?'F':'E',shared));const cells=special?{start:'H',received:'I',spent:'J',end:'K'}:{start:'F',received:'G',spent:'H',end:'I'};const byField={};for(const [field,col] of Object.entries(cells))byField[field]=parseMaterialCell(colText(row,col,shared),catalog,unknown);const names=new Set(Object.values(byField).flatMap(x=>Object.keys(x)));const gsm={};for(const name of names){const q={start:byField.start[name]??0,received:byField.received[name]??0,spent:byField.spent[name]??0,end:byField.end[name]??0};if(Object.values(q).some(x=>Math.abs(Number(x)||0)>1e-9))gsm[name]=q}let note=String(colText(row,special?'M':'K',shared)||'').trim();if(special&&/^[-+]?\d+(?:[.,]\d+)?$/.test(note))note='';if(special&&!note){const alt=String(colText(row,'O',shared)||'').trim();if(alt&&!/^[-+]?\d+(?:[.,]\d+)?$/.test(alt))note=alt}const motohours=special?(numCell(colText(row,'L',shared))??''):'';const any=date||number||odoStart!==null||odoEnd!==null||Object.keys(gsm).length||note;if(!any)continue;trips.push({date,number,odoStart:odoStart??'',odoEnd:odoEnd??'',motohours,unused:/неисп/i.test(note),note,gsm})}return trips}
        async function importMonth(templateBytes,vehicles,catalog){const files=await unzip(templateBytes),shared=sharedStrings(files),analyses=workbookEntries(files).map(e=>analyze(files,e,shared)),unknown=new Set(),statements=[],periodHits=new Map(),ignored=[];let recognized=0,totalTrips=0;for(const a of analyses){const title=cellRef(a.doc,'A1',shared),pp=periodFromTitle(title);if(pp){const k=JSON.stringify(pp);periodHits.set(k,(periodHits.get(k)||0)+1)}const v=vehicleForSheet(a,vehicles,shared);if(!v){ignored.push(a.name);continue}recognized++;const trips=parseNativeSheet(a,shared,v,catalog,unknown);if(trips.length){statements.push({vehicleId:v.id,sourceSheet:a.name,trips});totalTrips+=trips.length}}const best=[...periodHits.entries()].sort((a,b)=>b[1]-a[1])[0];if(!best)throw new Error('Не удалось определить расчётный период из заголовков листов.');const period=JSON.parse(best[0]);return {period,statements,recognized,totalSheets:analyses.length,totalTrips,ignored,unknownMaterials:[...unknown]}}
        function downloadBytes(bytes,name,mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'){const blob=new Blob([bytes],{type:mime}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
        
export { inspect, render, renderBook, importMonth, downloadBytes };
