import React, { useEffect, useState } from 'react'
import { Button, Field, Modal } from '../components/ui.jsx'
import { uid } from '../lib/domain.js'
import { RATE_PER_100KM, RATE_PER_MOTOHOUR, normalizeRateType, rateUnitLabel } from '../lib/vehicleMetrics.js'

const blank={shortNo:'',model:'',reg:'',baseRate:'',rateType:RATE_PER_100KM,tankCapacity:'',normText:'',hasMotohours:false}

export default function VehicleModal({open,onClose,state,mutate,notify,vehicle=null}){
  const[form,setForm]=useState(blank)
  useEffect(()=>{if(open){const initial=vehicle?{...blank,...vehicle}:blank;initial.rateType=normalizeRateType(initial.rateType);if(initial.rateType===RATE_PER_MOTOHOUR)initial.hasMotohours=true;setForm(initial)}},[open,vehicle?.id])
  const setRateType=value=>setForm(f=>{const rateType=normalizeRateType(value);return{...f,rateType,hasMotohours:rateType===RATE_PER_MOTOHOUR?true:f.hasMotohours}})
  const submit=e=>{e.preventDefault();const shortNo=String(form.shortNo||'').trim(),model=String(form.model||'').trim(),reg=String(form.reg||'').trim();if(!shortNo||!model)return notify('Укажите номер машины и модель.',true);if((state.vehicles||[]).some(v=>v.id!==vehicle?.id&&String(v.shortNo).trim().toLowerCase()===shortNo.toLowerCase()))return notify('Машина с таким номером уже есть.',true);const rateType=normalizeRateType(form.rateType),baseRate=form.baseRate===''?null:Number(form.baseRate);if(baseRate!==null&&(!Number.isFinite(baseRate)||baseRate<0))return notify('Норма расхода должна быть положительным числом.',true);const out={id:vehicle?.id||`vehicle_${uid()}`,shortNo,model,reg,baseRate,rateType,tankCapacity:form.tankCapacity===''?null:Number(form.tankCapacity),normText:String(form.normText||''),defaultMaterials:Array.isArray(vehicle?.defaultMaterials)?vehicle.defaultMaterials:[],hasMotohours:rateType===RATE_PER_MOTOHOUR||!!form.hasMotohours};mutate(next=>{const ix=(next.vehicles||[]).findIndex(v=>v.id===out.id);if(ix>=0)next.vehicles[ix]=out;else next.vehicles.push(out)});notify(vehicle?'Автомобиль обновлён':'Автомобиль добавлен');onClose()}
  const unit=rateUnitLabel(form)
  return <Modal open={open} onClose={onClose} wide title={vehicle?'Редактирование автомобиля':'Новый автомобиль'}><form onSubmit={submit}><div className="modal-body grid-2"><Field label="Номер машины"><input className="input" value={form.shortNo||''} onChange={e=>setForm(f=>({...f,shortNo:e.target.value}))}/></Field><Field label="Модель"><input className="input" value={form.model||''} onChange={e=>setForm(f=>({...f,model:e.target.value}))}/></Field><Field label="Регистрационный номер"><input className="input" value={form.reg||''} onChange={e=>setForm(f=>({...f,reg:e.target.value}))}/></Field><Field label="Тип нормы расхода"><select className="select" value={normalizeRateType(form.rateType)} onChange={e=>setRateType(e.target.value)}><option value={RATE_PER_100KM}>л / 100 км</option><option value={RATE_PER_MOTOHOUR}>л / моточас</option></select></Field><Field label={`Норма, ${unit}`}><input className="input" inputMode="decimal" value={form.baseRate??''} onChange={e=>setForm(f=>({...f,baseRate:e.target.value}))}/></Field><Field label="Вместимость бака, л"><input className="input" inputMode="decimal" value={form.tankCapacity??''} onChange={e=>setForm(f=>({...f,tankCapacity:e.target.value}))}/></Field><label className="toggle-card"><input type="checkbox" checked={!!form.hasMotohours} disabled={normalizeRateType(form.rateType)===RATE_PER_MOTOHOUR} onChange={e=>setForm(f=>({...f,hasMotohours:e.target.checked}))}/><span><b>Учёт моточасов</b><small>{normalizeRateType(form.rateType)===RATE_PER_MOTOHOUR?'Включён автоматически для нормы л/моточас':'Можно учитывать моточасы дополнительно к пробегу'}</small></span></label><Field className="span-2" label="Текст нормы / примечание"><textarea className="textarea vehicle-norm" value={form.normText||''} onChange={e=>setForm(f=>({...f,normText:e.target.value}))}/></Field></div><div className="modal-actions"><Button type="button" onClick={onClose}>Отмена</Button><Button primary type="submit">{vehicle?'Сохранить':'Добавить'}</Button></div></form></Modal>}
