import React from 'react'
import { Badge, Button, Card, Empty, cx } from './ui.jsx'
import { fmtDate, kmfmt, materialCellName, materialDisplayName, motohoursWorked, nfmt, nonZero, num, statementMaterialNames, tripMaterialNames, validateStatement } from '../lib/domain.js'

export function TripTable({ state, period, statement, vehicle, onEdit, onDelete }) {
  if(!statement.trips.length)return <Empty compact title="Машина не выезжала" text="Путёвок нет — ведомость считается обработанной как машина без выезда."/>
  const allErrors=validateStatement(state,statement,period).errors
  return <div className="table-wrap"><table className="data-table trips-table"><thead><tr><th>Дата</th><th>№</th><th>Одометр до</th><th>После</th><th>Км</th>{vehicle.hasMotohours&&<><th>М/ч до</th><th>После</th><th>М/ч</th></>}<th>ГСМ: расход / остаток</th><th>Примечание</th><th>Действия</th></tr></thead><tbody>{statement.trips.map(t=>{const prefix=`Путёвка №${t.number||'?'} (${fmtDate(t.date)})`,errs=allErrors.filter(e=>e.startsWith(prefix)),a=num(t.odoStart),b=num(t.odoEnd),mhStart=num(t.motohoursStart),mhEnd=num(t.motohoursEnd),mh=motohoursWorked(t),gsm=tripMaterialNames(t).map(m=>{const q=t.gsm?.[m]||{},spent=num(q.spent),end=num(q.end),parts=[];if(spent!==null&&nonZero(state,spent))parts.push(`−${nfmt(spent)}`);if(end!==null&&nonZero(state,end))parts.push(`ост. ${nfmt(end)}`);return parts.length?<span key={m}><b>{materialCellName(m)}</b> {parts.join(' / ')}</span>:null}).filter(Boolean);return <tr key={t.id} className={cx('clickable hover-row',errs.length&&'row-bad',t.unused&&'row-unused')} onClick={()=>onEdit(t)}><td><b>{fmtDate(t.date)}</b></td><td><b>{t.number}</b>{t.unused&&<Badge>неисп.</Badge>}</td><td className="num">{kmfmt(t.odoStart)}</td><td className="num">{kmfmt(t.odoEnd)}</td><td className="num"><b>{a!==null&&b!==null?kmfmt(b-a):'—'}</b></td>{vehicle.hasMotohours&&<><td className="num">{mhStart===null?'—':nfmt(mhStart)}</td><td className="num">{mhEnd===null?'—':nfmt(mhEnd)}</td><td className="num"><b>{mh===null?'—':nfmt(mh)}</b></td></>}<td><div className="trip-gsm">{gsm}</div></td><td>{t.note||'—'}</td><td className="actions-cell"><div className="row-actions">{errs.length?<Badge tone="bad">{errs.length}</Badge>:<Badge tone="ok">✓</Badge>}<Button small danger onClick={e=>{e.stopPropagation();onDelete(t)}}>× Удалить</Button></div></td></tr>})}</tbody></table></div>
}

export function BalancePanel({ statement, total }) { const mats=statementMaterialNames(statement); return <Card className="balance-card"><h3>Итоги месяца</h3>{mats.length?mats.map(m=><div className="total-block" key={m}><b>{materialDisplayName(m)}</b><div><span>Начало</span><strong>{nfmt(total[m]?.start)} л</strong></div><div><span>Получено</span><strong>{nfmt(total[m]?.received)} л</strong></div><div><span>Расход</span><strong>{nfmt(total[m]?.spent)} л</strong></div><div><span>Остаток</span><strong>{nfmt(total[m]?.end)} л</strong></div></div>):<span className="muted">Нет ГСМ</span>}</Card> }
export function CheckPanel({ status }) { return <Card className="side-card"><div className="side-card-head"><h3>Проверка</h3><Badge tone={status.tone}>{status.label}</Badge></div>{status.check.errors.length>0&&<div className="check-list bad"><b>Ошибки</b>{status.check.errors.slice(0,6).map((e,i)=><span key={i}>{e}</span>)}{status.check.errors.length>6&&<small>+ ещё {status.check.errors.length-6}</small>}</div>}{status.check.warnings.length>0&&<div className="check-list warn"><b>Замечания</b>{status.check.warnings.slice(0,5).map((e,i)=><span key={i}>{e}</span>)}</div>}{!status.check.errors.length&&!status.check.warnings.length&&<div className="all-good">✓ Контроль пройден</div>}</Card> }
export function CarryPanel({ statement, onRefresh }) { return <Card className="side-card"><div className="side-card-head"><h3>Перенос</h3><Button small onClick={onRefresh}>Обновить</Button></div>{statement.opening?<><p className="muted">Из периода {statement.opening.sourceLabel}</p><div className="carry-value"><span>Одометр</span><b>{kmfmt(statement.opening.odo)}</b></div>{statement.opening.motohours!=null&&<div className="carry-value"><span>Моточасы</span><b>{nfmt(statement.opening.motohours)}</b></div>}{Object.entries(statement.opening.gsm||{}).map(([m,v])=><div className="carry-value" key={m}><span>{materialDisplayName(m)}</span><b>{nfmt(v)} л</b></div>)}{statement.opening.sourceHasErrors&&<div className="mini-warning">В исходной ведомости есть ошибки.</div>}</>:<p className="muted">Предыдущая заполненная ведомость этой машины не найдена.</p>}</Card> }
