import React, { startTransition, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Button, Card, ConfirmDialog, NavButton, TitleBar, cx } from './components/ui.jsx'
import HomeView from './views/HomeView.jsx'
import PeriodView from './views/PeriodView.jsx'
import StatementView from './views/StatementView.jsx'
import PreviewView from './views/PreviewView.jsx'
import VehiclesView from './views/VehiclesView.jsx'
import CatalogView from './views/CatalogView.jsx'
import HistoryView from './views/HistoryView.jsx'
import PeriodModal from './modals/PeriodModal.jsx'
import MaterialModal from './modals/MaterialModal.jsx'
import VehicleModal from './modals/VehicleModal.jsx'
import SettingsModal from './modals/SettingsModal.jsx'
import useHistoryState from './hooks/useHistoryState.js'
import { groupPeriods } from './lib/viewData.js'
import {
  DEFAULT_STATE, STORAGE_VERSION, clone, createStatement, fmtDate, migrateState, periodDisplayName,
  periodMonthName, periodYear, safeFile, sortedPeriods, uid, validateStatement, vehicleOf
} from './lib/domain.js'
import { xlsxModel } from './lib/document.js'
import { loadTemplateEngine, reportRendererError } from './lib/runtime.js'
import { countForm, RU_FORMS } from './lib/ru.js'

export default function App(){
  const history=useHistoryState(migrateState(DEFAULT_STATE),50)
  const state=history.state
  const [ready,setReady]=useState(false)
  const [view,setView]=useState({name:'home',periodId:null,statementId:null,vehicleId:null})
  const [periodModal,setPeriodModal]=useState(false),[settingsModal,setSettingsModal]=useState(false),[materialModal,setMaterialModal]=useState(false),[vehicleModal,setVehicleModal]=useState({open:false,vehicle:null})
  const [toast,setToast]=useState(null),[appInfo,setAppInfo]=useState(null),[loadError,setLoadError]=useState(''),[saveError,setSaveError]=useState(''),[confirmDialog,setConfirmDialog]=useState(null)
  const saveTimer=useRef(null),toastTimer=useRef(null),stateRef=useRef(state),readyRef=useRef(ready),loadErrorRef=useRef(loadError),busyRef=useRef(''),confirmResolver=useRef(null)
  stateRef.current=state;readyRef.current=ready;loadErrorRef.current=loadError

  const notify=useCallback((message,bad=false)=>{setToast({message,bad});clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(null),3000)},[])
  const confirmAction=useCallback(options=>new Promise(resolve=>{if(confirmResolver.current)confirmResolver.current(false);confirmResolver.current=resolve;setConfirmDialog(typeof options==='string'?{message:options}:options)}),[])
  const resolveConfirm=useCallback(result=>{const resolve=confirmResolver.current;confirmResolver.current=null;setConfirmDialog(null);resolve?.(result)},[])
  const runExclusive=async(label,operation)=>{if(busyRef.current){notify(`Дождитесь завершения операции «${busyRef.current}».`,true);return null}busyRef.current=label;try{return await operation()}catch(error){reportRendererError(`operation:${label}`,error);notify(`Операция «${label}» не выполнена: ${error?.message||error}`,true);return null}finally{busyRef.current=''}}
  useEffect(()=>()=>clearTimeout(toastTimer.current),[])

  useEffect(()=>{;(async()=>{try{let loaded=null;if(window.desktopAPI?.isElectron){const result=await window.desktopAPI.loadData();setAppInfo(await window.desktopAPI.getAppInfo());if(!result?.success)throw new Error(result?.error||'Не удалось прочитать локальную базу.');loaded=result.data;if(result.recoveredFrom){const source=result.recoveredFrom==='backup'?'резервной копии базы':'временного файла незавершённого сохранения';notify(`База восстановлена из ${source}. Проверьте последние изменения.`,true)}}else{const raw=localStorage.getItem('gsm_vedomosti_v12')||localStorage.getItem('gsm_vedomosti_v02')||localStorage.getItem('gsm_vedomosti_v01');if(raw)loaded=JSON.parse(raw)}if(loaded)history.setState(migrateState(loaded));history.resetHistory();setLoadError('')}catch(error){reportRendererError('startup:load',error);const message=error?.message||String(error);setLoadError(message);notify(`База не загружена: ${message}`,true)}finally{setReady(true)}})()},[])

  useEffect(()=>{if(!ready||loadError||state.settings.autosave===false)return;clearTimeout(saveTimer.current);let idleId=null;const save=async()=>{try{if(window.desktopAPI?.isElectron){const result=await window.desktopAPI.saveData(state);if(!result?.success)throw new Error(result?.error||'Не удалось сохранить локальную базу.')}else localStorage.setItem('gsm_vedomosti_v12',JSON.stringify(state));setSaveError('')}catch(error){reportRendererError('autosave',error);const message=error?.message||String(error);setSaveError(message);notify(`Автосохранение не выполнено: ${message}`,true)}};saveTimer.current=setTimeout(()=>{if(typeof window.requestIdleCallback==='function')idleId=window.requestIdleCallback(save,{timeout:1800});else save()},Math.max(0,Number(state.settings.autosaveDelay)||0));return()=>{clearTimeout(saveTimer.current);if(idleId!==null&&typeof window.cancelIdleCallback==='function')window.cancelIdleCallback(idleId)}},[state,ready,loadError])

  useEffect(()=>{const api=window.desktopAPI;if(!api?.isElectron||typeof api.saveDataSync!=='function')return;const flushBeforeClose=event=>{if(!readyRef.current||loadErrorRef.current)return;const result=api.saveDataSync(stateRef.current);if(!result?.success){event.preventDefault();event.returnValue=false;setSaveError(result?.error||'Не удалось сохранить локальную базу перед закрытием.')}};window.addEventListener('beforeunload',flushBeforeClose);return()=>window.removeEventListener('beforeunload',flushBeforeClose)},[])
  useEffect(()=>{const handler=e=>{if(!(e.ctrlKey||e.metaKey))return;const tag=e.target?.tagName?.toLowerCase(),editing=['input','textarea','select'].includes(tag)||e.target?.isContentEditable;if(editing)return;if(e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?history.redo():history.undo()}else if(e.key.toLowerCase()==='y'){e.preventDefault();history.redo()}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[history.undo,history.redo])

  const periods=useMemo(()=>sortedPeriods(state),[state]),groupedPeriods=useMemo(()=>groupPeriods(periods),[periods])
  const activePeriod=state.periods.find(p=>p.id===view.periodId),activeStatement=activePeriod?.statements?.find(s=>s.id===view.statementId),activeVehicle=activeStatement?vehicleOf(state,activeStatement.vehicleId):(view.vehicleId?vehicleOf(state,view.vehicleId):null)
  const mutate=fn=>history.commit(prev=>{const next=clone(prev);fn(next);return next})
  const navigate=next=>startTransition(()=>setView(next)),goHome=()=>navigate({name:'home',periodId:null,statementId:null,vehicleId:null}),goPeriod=periodId=>navigate({name:'period',periodId,statementId:null,vehicleId:null}),goStatement=(periodId,statementId)=>navigate({name:'statement',periodId,statementId,vehicleId:null}),goHistory=vehicleId=>navigate({name:'history',periodId:null,statementId:null,vehicleId})

  async function saveCurrent(showSuccess=true){if(loadError){notify('Сохранение заблокировано: сначала восстановите или сбросьте повреждённую базу.',true);return{success:false,error:loadError}}try{if(window.desktopAPI?.isElectron){const result=await window.desktopAPI.saveData(stateRef.current);if(!result?.success)throw new Error(result?.error||'Не удалось сохранить локальную базу.')}else localStorage.setItem('gsm_vedomosti_v12',JSON.stringify(stateRef.current));setSaveError('');if(showSuccess)notify('Данные сохранены');return{success:true}}catch(error){reportRendererError('save:manual',error);const message=error?.message||String(error);setSaveError(message);notify(`Не удалось сохранить данные: ${message}`,true);return{success:false,error:message}}}
  async function closeApp(){const api=window.desktopAPI;if(!api?.isElectron)return;if(loadError){if(await confirmAction({title:'Закрыть без сохранения?',message:'Локальная база не была загружена. Закрыть приложение без сохранения?',confirmText:'Закрыть',danger:true}))await api.closeWindow();return}const saved=await saveCurrent(false);if(saved.success)await api.closeWindow()}
  async function startFreshDatabase(){if(!await confirmAction({title:'Создать пустую базу?',message:'Текущая повреждённая база не будет перезаписана без резервного файла восстановления.',confirmText:'Создать базу',danger:true}))return;const fresh=migrateState(DEFAULT_STATE);try{if(window.desktopAPI?.isElectron){const result=await window.desktopAPI.saveData(fresh);if(!result?.success)throw new Error(result?.error||'Не удалось создать новую базу.')}else localStorage.setItem('gsm_vedomosti_v12',JSON.stringify(fresh));history.setState(fresh);history.resetHistory();setLoadError('');setSaveError('');goHome();notify('Создана новая пустая база')}catch(error){reportRendererError('database:new',error);notify(`Не удалось создать новую базу: ${error?.message||error}`,true)}}
  async function exportBackup(){return runExclusive('резервное копирование',async()=>{const name=`ГСМ_универсальная_копия_${new Date().toISOString().slice(0,10)}.gsmbackup`;if(window.desktopAPI?.isElectron){const r=await window.desktopAPI.exportBackup(state,name);if(r?.success)notify('Резервная копия сохранена');else if(!r?.canceled)notify(r?.error||'Ошибка сохранения',true)}else notify('Резервная копия доступна в настольной сборке.',true)})}
  async function importBackup(){return runExclusive('восстановление резервной копии',async()=>{if(!window.desktopAPI?.isElectron)return notify('Импорт резервной копии доступен в настольной сборке.',true);const r=await window.desktopAPI.importBackup();if(r?.success){const sourceSchema=Number(r.meta?.dataSchemaVersion??r.data?.version??0);if(Number.isFinite(sourceSchema)&&sourceSchema>STORAGE_VERSION){notify(`Эта резервная копия создана более новой версией данных (схема ${sourceSchema}). Обновите приложение перед восстановлением.`,true);return}}if(r?.success&&await confirmAction({title:'Восстановить резервную копию?',message:'Текущие данные приложения будут заменены данными из выбранной копии.',confirmText:'Восстановить',danger:true})){try{const restored=migrateState(r.data),saved=await window.desktopAPI.saveData(restored);if(!saved?.success)throw new Error(saved?.error||'Не удалось записать восстановленную базу на диск.');history.commit(restored);setLoadError('');setSaveError('');goHome();notify('Резервная копия восстановлена')}catch(error){reportRendererError('backup:restore',error);notify(`Резервную копию не удалось восстановить: ${error?.message||error}`,true)}}else if(!r?.canceled&&!r?.success)notify(r?.error||'Не удалось открыть копию',true)})}

  async function loadTemplateBytes(){if(!window.desktopAPI?.isElectron)throw new Error('Шаблон доступен только в настольной версии.');const r=await window.desktopAPI.loadTemplate();if(!r?.success||!r.bytes)throw new Error(r?.error||'Сначала загрузите исходную Excel-книгу в настройках.');return new Uint8Array(r.bytes)}
  async function saveRenderedXlsx(bytes,filename){const r=await window.desktopAPI.saveBinary(bytes,filename,[{name:'Excel',extensions:['xlsx']}]);if(r?.success)notify('XLSX сохранён');else if(!r?.canceled)notify(r?.error||'Ошибка сохранения XLSX',true)}
  async function exportStatement(p,st){return runExclusive('экспорт ведомости',async()=>{const v=vehicleOf(state,st.vehicleId),check=validateStatement(state,st,p);if(check.errors.length&&!await confirmAction({title:'Экспортировать с ошибками?',message:`Найдено ${countForm(check.errors.length,RU_FORMS.error)}. XLSX всё равно будет создан.`,confirmText:'Экспортировать',danger:false}))return;try{const{render}=await loadTemplateEngine(),bytes=await render(await loadTemplateBytes(),xlsxModel(state,p,st,v));await saveRenderedXlsx(bytes,safeFile(`Ведомость_${v.shortNo}_${p.start}_${p.end}.xlsx`))}catch(e){reportRendererError('xlsx:exportStatement',e);notify(e.message,true)}})}
  async function exportPeriod(p){return runExclusive('экспорт периода',async()=>{const errors=(p.statements||[]).reduce((n,st)=>n+validateStatement(state,st,p).errors.length,0);if(errors&&!await confirmAction({title:'Экспортировать период с ошибками?',message:`В периоде найдено ${countForm(errors,RU_FORMS.error)}.`,confirmText:'Экспортировать',danger:false}))return;try{const models=(state.vehicles||[]).map(base=>{const v=vehicleOf(state,base.id),st=(p.statements||[]).find(s=>s.vehicleId===base.id)||{id:`idle_${base.id}`,vehicleId:base.id,materials:[],trips:[],opening:{odo:null,gsm:{}}};return xlsxModel(state,p,st,v)}),{renderBook}=await loadTemplateEngine(),bytes=await renderBook(await loadTemplateBytes(),models);await saveRenderedXlsx(bytes,safeFile(`Ведомости_ГСМ_${periodMonthName(p)}_${periodYear(p)}.xlsx`))}catch(e){reportRendererError('xlsx:exportPeriod',e);notify(e.message,true)}})}
  async function importMonthBook(file){return runExclusive('импорт Excel',async()=>{if(!file)return;if(file.size>64*1024*1024)return notify('Файл XLSX больше 64 МБ. Импорт заблокирован для защиты памяти 32-битной сборки.',true);try{const{importMonth}=await loadTemplateEngine(),result=await importMonth(await file.arrayBuffer(),state.vehicles||[],state.catalog),pp=result.period,exists=state.periods.some(x=>x.start===pp.start&&x.end===pp.end);if(exists&&!await confirmAction({title:'Заменить существующий период?',message:`Период ${fmtDate(pp.start)} — ${fmtDate(pp.end)} уже существует.`,confirmText:'Заменить',danger:true}))return;const next=clone(state);next.periods=next.periods.filter(x=>!(x.start===pp.start&&x.end===pp.end));for(const name of result.unknownMaterials||[])if(!next.catalog.some(x=>x.name===name))next.catalog.push({id:`import_${uid()}`,name,category:/^Д[тТ](?=\s|$)/i.test(name)?'Топливо':'Масло',unit:'л',aliases:[name],sourceVehicles:[],sourceCount:0,active:true});const p={id:uid(),reportMonth:pp.reportMonth,start:pp.start,end:pp.end,statements:[],importInfo:{file:file.name,importedAt:new Date().toISOString(),recognizedSheets:result.recognized,totalSheets:result.totalSheets,totalTrips:result.totalTrips,skippedOutOfPeriod:result.skippedOutOfPeriod||0,ignoredSheets:result.ignored}};next.periods.push(p);for(const raw of result.statements){const v=vehicleOf(next,raw.vehicleId);if(!v)continue;const st=createStatement(next,p,v);st.trips=raw.trips.map(t=>({...t,id:uid(),seq:Date.now()+Math.random(),gsm:Object.fromEntries(Object.entries(t.gsm||{}).map(([m,q])=>[m,{...q,_carried:false,_autoTarget:''}]))}));p.statements.push(st)}history.commit(migrateState(next));goPeriod(p.id);notify(`Импортировано ${countForm(result.totalTrips,RU_FORMS.trip)} · ${countForm(result.statements.length,RU_FORMS.vehicle)}${result.skippedOutOfPeriod?` · пропущено строк прошлого периода: ${result.skippedOutOfPeriod}`:''}`)}catch(e){reportRendererError('xlsx:importMonth',e);notify(`Ошибка импорта книги: ${e.message}`,true)}})}
  async function deletePeriod(periodId){const p=state.periods.find(x=>x.id===periodId);if(!p)return;if(!await confirmAction({title:'Удалить период?',message:`${periodDisplayName(p)} и все его ведомости будут удалены.`,confirmText:'Удалить период',danger:true}))return;mutate(next=>{next.periods=next.periods.filter(x=>x.id!==periodId)});goHome()}
  async function deleteYear(year){const count=state.periods.filter(p=>periodYear(p)===Number(year)).length;if(!await confirmAction({title:`Удалить ${year} год?`,message:`Будут удалены ${countForm(count,RU_FORMS.period)} этого года.`,confirmText:'Удалить год',danger:true}))return;mutate(next=>{next.periods=next.periods.filter(p=>periodYear(p)!==Number(year))});goHome()}
  async function printStatement(p,st){return runExclusive('печать',async()=>{const v=vehicleOf(state,st.vehicleId),check=validateStatement(state,st,p);if(check.errors.length&&!await confirmAction({title:'Печатать с ошибками?',message:`Найдено ${countForm(check.errors.length,RU_FORMS.error)}.`,confirmText:'Печатать',danger:false}))return;if(!window.desktopAPI?.isElectron)return window.print();const direct=state.settings.directPrint&&state.settings.preferredPrinter;try{const{renderHtml}=await loadTemplateEngine(),html=await renderHtml(await loadTemplateBytes(),xlsxModel(state,p,st,v),true),r=await window.desktopAPI.printHtml(html,{silent:!!direct,deviceName:direct?state.settings.preferredPrinter:''});if(r?.success)notify(direct?'Отправлено на принтер':'Печать завершена');else notify(r?.error||'Ошибка печати',true)}catch(error){reportRendererError('print',error);notify(`Ошибка печати: ${error?.message||error}`,true)}})}
  const getPreviewHtml=useCallback(async()=>{if(!activePeriod||!activeStatement||!activeVehicle)throw new Error('Ведомость не выбрана.');const{renderHtml}=await loadTemplateEngine();return renderHtml(await loadTemplateBytes(),xlsxModel(state,activePeriod,activeStatement,activeVehicle),false)},[state,activePeriod?.id,activeStatement?.id,activeVehicle?.id])

  if(!ready)return <div className="loading"><div className="loader"/><b>ГСМ Ведомости</b><span>Загрузка локальной базы…</span></div>
  if(loadError)return <RecoveryScreen appInfo={appInfo} error={loadError} onRestore={importBackup} onReset={startFreshDatabase} onClose={()=>window.desktopAPI?.closeWindow?.()} confirmDialog={confirmDialog} resolveConfirm={resolveConfirm}/>

  return <div className={cx('desktop-root',state.settings.performanceMode!==false&&'performance-mode')}>
    <TitleBar appInfo={appInfo} onClose={closeApp} onUndo={history.undo} onRedo={history.redo} canUndo={history.canUndo} canRedo={history.canRedo}/>
    <div className="app-shell">
      <aside className="sidebar"><div className="brand"><div className="brand-mark">Г</div><div><b>Рабочая база</b><span>РАСЧЁТНЫЕ ВЕДОМОСТИ ГСМ</span></div></div><nav className="main-nav"><NavButton active={view.name==='home'} onClick={goHome} icon="⌂" label="Обзор периодов"/><NavButton active={view.name==='vehicles'||view.name==='history'} onClick={()=>navigate({name:'vehicles'})} icon="▣" label="Автомобили"/><NavButton active={view.name==='catalog'} onClick={()=>navigate({name:'catalog'})} icon="◫" label="Справочник ГСМ"/></nav><details className="period-tree" open><summary><span>▾</span> Периоды</summary><div className="period-tree-body">{groupedPeriods.map(([year,items])=><details className="year-tree" key={year} defaultOpen={items.some(p=>p.id===view.periodId)}><summary><span>▾</span><b>{year}</b><small>{items.length}</small></summary><div className="month-tree">{items.map(p=><button key={p.id} onClick={()=>goPeriod(p.id)} className={cx('month-tree-item',view.periodId===p.id&&['period','statement','preview'].includes(view.name)&&'active')}><b>{periodMonthName(p)}</b><span>{fmtDate(p.start)} — {fmtDate(p.end)}</span></button>)}</div></details>)}{!periods.length&&<div className="side-empty">Периодов пока нет</div>}</div></details><div className="sidebar-spacer"/><div className="side-caption">Сервис</div><button className="side-link" onClick={()=>setSettingsModal(true)}>⚙ Настройки</button><button className="side-link" onClick={()=>saveCurrent(true)}>💾 Сохранить</button><button className="side-link" onClick={exportBackup}>⇩ Сделать резервную копию</button><button className="side-link" onClick={importBackup}>⇧ Восстановить из копии</button><div className="app-meta"><span className={cx('status-dot',saveError&&'bad',state.settings.autosave===false&&!saveError&&'off')}/><div><b>{saveError?'Ошибка сохранения':state.settings.autosave===false?'Автосохранение выключено':'Автосохранение активно'}</b><span>{saveError||(state.settings.autosave===false?'Сохранение вручную или при выходе':appInfo?.version?`Версия ${appInfo.version}`:'React · Electron')}</span></div></div></aside>
      <main className="main-content">{view.name==='home'&&<HomeView state={state} periods={periods} onNew={()=>setPeriodModal(true)} onOpen={goPeriod} onImport={importMonthBook} onDeletePeriod={deletePeriod} onDeleteYear={deleteYear}/>} {view.name==='period'&&activePeriod&&<PeriodView state={state} period={activePeriod} mutate={mutate} onOpen={st=>goStatement(activePeriod.id,st.id)} onExport={()=>exportPeriod(activePeriod)} onHistory={goHistory}/>} {view.name==='statement'&&activePeriod&&activeStatement&&activeVehicle&&<StatementView state={state} period={activePeriod} statement={activeStatement} vehicle={activeVehicle} mutate={mutate} onBack={()=>goPeriod(activePeriod.id)} onHistory={()=>goHistory(activeVehicle.id)} onPreview={()=>setView({...view,name:'preview'})} onExport={()=>exportStatement(activePeriod,activeStatement)} onPrint={()=>printStatement(activePeriod,activeStatement)} notify={notify} confirmAction={confirmAction}/>} {view.name==='preview'&&activePeriod&&activeStatement&&activeVehicle&&<PreviewView vehicle={activeVehicle} onBack={()=>setView({...view,name:'statement'})} onExport={()=>exportStatement(activePeriod,activeStatement)} onPrint={()=>printStatement(activePeriod,activeStatement)} getPreviewHtml={getPreviewHtml}/>} {view.name==='vehicles'&&<VehiclesView state={state} mutate={mutate} onHistory={goHistory} onAdd={()=>setVehicleModal({open:true,vehicle:null})} onEdit={vehicle=>setVehicleModal({open:true,vehicle})} notify={notify} confirmAction={confirmAction}/>} {view.name==='catalog'&&<CatalogView state={state} mutate={mutate} onAdd={()=>setMaterialModal(true)} notify={notify} confirmAction={confirmAction}/>} {view.name==='history'&&activeVehicle&&<HistoryView state={state} vehicle={activeVehicle} onBack={()=>navigate({name:'vehicles'})} onOpen={(p,st)=>goStatement(p.id,st.id)}/>}</main>
      <PeriodModal open={periodModal} onClose={()=>setPeriodModal(false)} state={state} mutate={mutate} notify={notify} onCreated={p=>{setPeriodModal(false);goPeriod(p.id)}}/>
      <SettingsModal open={settingsModal} onClose={()=>setSettingsModal(false)} state={state} mutate={mutate} notify={notify} appInfo={appInfo} confirmAction={confirmAction}/>
      <MaterialModal open={materialModal} onClose={()=>setMaterialModal(false)} state={state} mutate={mutate} notify={notify}/>
      <VehicleModal open={vehicleModal.open} vehicle={vehicleModal.vehicle} onClose={()=>setVehicleModal({open:false,vehicle:null})} state={state} mutate={mutate} notify={notify}/>
      <ConfirmDialog dialog={confirmDialog} onResolve={resolveConfirm}/>
      {toast&&<div className={cx('toast',toast.bad&&'toast-bad')}>{toast.message}</div>}
    </div>
  </div>
}

function RecoveryScreen({appInfo,error,onRestore,onReset,onClose,confirmDialog,resolveConfirm}){return <div className="desktop-root performance-mode"><TitleBar appInfo={appInfo} onClose={onClose}/><div className="recovery-screen"><Card className="recovery-card"><div className="recovery-icon">!</div><h1>Локальная база не загружена</h1><p>Приложение остановило автоматическое сохранение, чтобы не перезаписать существующие данные пустой базой.</p><div className="recovery-error">{error}</div>{appInfo?.dataPath&&<div className="recovery-path">Файл базы: {appInfo.dataPath}</div>}<div className="toolbar recovery-actions"><Button primary onClick={onRestore}>Восстановить из копии</Button><Button danger onClick={onReset}>Создать пустую базу</Button><Button onClick={onClose}>Закрыть</Button></div></Card></div><ConfirmDialog dialog={confirmDialog} onResolve={resolveConfirm}/></div>}
